/*
 * File: app/view/CompanyStockChart.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ComStat.view.CompanyStockChart', {
    extend: 'Ext.chart.CartesianChart',
    alias: 'widget.companystockchart',

    config: {
        store: 'StockDataStore',
        axes: [
            {
                type: 'time',
                fields: [
                    'date'
                ]
            },
            {
                type: 'numeric',
                fields: [
                    'open'
                ],
                grid: {
                    odd: {
                        fill: '#e8e8e8'
                    }
                },
                position: 'left'
            }
        ],
        series: [
            {
                type: 'line',
                style: {
                    smooth: true,
                    stroke: 'rgb(0,200,0)',
                    fill: 'rgba(0,200,0,0.3)'
                },
                xField: 'date',
                yField: 'open'
            }
        ],
        interactions: [
            {
                type: 'panzoom'
            }
        ]
    }

});