/*
 * File: app/controller/CompanyController.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ComStat.controller.CompanyController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            navigation: '.companynavigation',
            mainView: '.mainview',
            chartContainer: '.chartcontainer',
            companyDetail: '.companydetail'
        },

        control: {
            ".companynavigation .list": {
                itemtap: 'showDetailView'
            },
            "[action='toggleChart']": {
                tap: 'toggleChartView'
            },
            "navigationview": {
                activeitemchange: 'onNavigationviewActiveItemChange'
            }
        }
    },

    showDetailView: function(dataview, index, target, record, e, eOpts) {
        var id = record.data.id,
            store = Ext.StoreManager.lookup('StockDataStore');
        store.getProxy().setUrl('http://localhost:4000/api/stock-data-'+id+'.json');

        var nav = this.getNavigation(),
            detail = Ext.create('ComStat.view.CompanyDetail', {
                title: record.data.name,
                record: record
            });
        nav.push(detail);

    },

    toggleChartView: function(button, e, eOpts) {
        var main = this.getMainView();
        var cont = this.getChartContainer();
        var titlebar = cont.child('titlebar');


        if (main.getActiveItem().id.match(/chartcontainer/)) {
            main.setActiveItem('companynavigation');
            button.setText('show chart');
            cont.removeAll();
        } else {
            if (titlebar.getTitle().match(/Bar/)) {
                // add a CompanyBarChart to the chart container
                cont.add({xtype:'companybarchart'});
            } else {
                Ext.StoreManager.lookup('StockDataStore').load();
                // add a CompanyStockChart to the chart container
            }
            main.setActiveItem('chartcontainer');
            button.setText('hide chart');
        }

    },

    onNavigationviewActiveItemChange: function(container, value, oldValue, eOpts) {
        var chartContainer = this.getChartContainer();
        var titlebar = chartContainer.child('titlebar');

        if (value.id.match(/ext-list/)) {
            titlebar.setTitle('Bar chart');
        } else {
            titlebar.setTitle('Line chart');
        }

    }

});